@startuml
'02_DBモデリング2
' 入れ子構造

entity users {
  + id [PK]
  --
  name
  is_delete
}

entity user_channels {
  + id [PK]
  --
  user_id
  channel_id
  is_delete
}

entity channels {
  + id [PK]
  --
  name
}

entity messages {
  + id [PK]
  --
  user_id
  channel_id
  content
  left
  right
  created_at
}

users          ||--o{ user_channels
channels       ||--o{ user_channels
channels       ||--o{ messages
users          ||--o{ messages

' 横断機能はユーザーの所属しているチャネルを取得してそのメッセージを取得し、
' それに紐付くスレッドを取得すれば検索できるはず

@enduml