@startuml
'02_DBモデリング2

entity users {
  + id [PK]
  --
  name
  is_delete
}

entity user_channels {
  + id [PK]
  --
  user_id
  channel_id
  is_delete
}

entity channels {
  + id [PK]
  --
  name
}

entity messages {
  + id [PK]
  --
  user_id
  channel_id
  content
  created_at
}

entity thread_messages {
  + id [PK]
  --
  message_id
  content
  created_at
}

users          --|{ user_channels
channels       --|{ user_channels
channels       --|{ messages
messages       --|{ thread_messages
users          --|{ messages

' 横断機能はユーザーの所属しているチャネルを取得してそのメッセージを取得し、
' それに紐付くスレッドを取得すれば検索できるはず

@enduml