@startuml
'03_DBモデリング3
' 閉包テーブル

entity users {
  + id [PK]
  --
  name
  is_delete
}

entity user_directory {
  + id [PK]
  --
  user_id
  directory_id
  is_delete
}

entity directory {
  + id [PK]
  --
  name
  is_delete
}

entity directory_relation {
  + id [PK]
  --
  ancestor
  descendant
}

entity document {
  + id [PK]
  --
  name
  content
  directory_id
  user_id
  is_delete
}

entity document_history {
  + id [PK]
  --
  name
  content
  document_id
  directory_id
  user_id
  is_delete
}

users      ||--o{ user_directory
directory  ||--o{ user_directory
users  ||--o{ document
directory  ||--o{ document
users  ||--o{ document_history
directory  ||--o{ document_history
directory  ||--o{ directory_relation
document   ||--o{ document_history

'参考
' https://qiita.com/fktnkit/items/57033c10b41b5747dbea#%E4%BB%A3%E6%9B%BF%E3%83%84%E3%83%AA%E3%83%BC%E3%83%A2%E3%83%87%E3%83%AB

@enduml